"""Queue-facing ideation service.

This module owns the boundary between the mechanical queue and the AI ideation
entrypoint. The queue runner may ask for one actionable spec, but it should not
parse provider failures or enqueue READY specs itself.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable

import yaml


EXCLUDE_STATUSES = {"DRAFT", "REJECT", "PROPOSAL_ONLY"}


class QueueIdeationService:
    def __init__(
        self,
        *,
        repo_root: Path,
        load_state: Callable[[], dict[str, Any]],
        save_state: Callable[[dict[str, Any]], None],
        write_status: Callable[[str, dict[str, Any] | None], None],
        audit: Callable[[str, dict[str, Any] | None], None],
        log: Callable[[str], None],
        mark_history: Callable[[dict[str, Any], dict[str, Any], str, str], None],
        rel: Callable[[Path], str],
        now_iso: Callable[[], str],
        ideation_env: Callable[[], dict[str, str]],
        timeout_seconds: int = 180,
    ) -> None:
        self.repo_root = repo_root
        self.load_state = load_state
        self.save_state = save_state
        self.write_status = write_status
        self.audit = audit
        self.log = log
        self.mark_history = mark_history
        self.rel = rel
        self.now_iso = now_iso
        self.ideation_env = ideation_env
        self.timeout_seconds = timeout_seconds

    def enqueue_ready_spec(self, state: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:
        spec_raw = payload.get("spec_path")
        if not spec_raw:
            raise ValueError("ideation returned READY without spec_path")
        spec_path = Path(str(spec_raw))
        if not spec_path.is_absolute():
            spec_path = self.repo_root / spec_path
        spec = yaml.safe_load(spec_path.read_text(encoding="utf-8")) or {}
        if not isinstance(spec, dict):
            raise ValueError(f"{self.rel(spec_path)} root must be dict")
        run_id = str(spec.get("run_id") or spec_path.parent.name)
        queue = state.get("queue")
        if not isinstance(queue, list):
            raise ValueError("research_queue.queue must be list")
        for item in queue:
            if isinstance(item, dict) and (item.get("id") == run_id or item.get("spec_path") == self.rel(spec_path)):
                return {"item_id": run_id, "spec_path": self.rel(spec_path), "already_present": True}
        automation = spec.get("automation") if isinstance(spec.get("automation"), dict) else {}
        item = {
            "id": run_id,
            "family": str(spec.get("family") or (spec.get("proposal") or {}).get("family") or "auto_deepseek_ideation"),
            "status": "queued",
            "spec_path": self.rel(spec_path),
            "process_pattern": run_id,
            "sync_paths": automation.get("sync_paths") if isinstance(automation.get("sync_paths"), list) else [],
            "discovered_at": self.now_iso(),
            "source": "project_owned_ideation",
        }
        queue.append(item)
        state["queue"] = queue
        escalation = state.get("escalation")
        if isinstance(escalation, dict) and escalation.get("status") == "blocked_awaiting_user":
            escalation["status"] = "auto_resolved"
            escalation["resolved_at"] = self.now_iso()
            escalation["resolution_reason"] = "old directions exhausted; registered provider available for new project-owned ideation"
        self.save_state(state)
        self.mark_history(state, item, "queued", "queued READY spec generated by project-owned ideation")
        self.save_state(state)
        return {"item_id": run_id, "spec_path": self.rel(spec_path), "already_present": False}

    def generate_next_spec_if_idle(self, state: dict[str, Any]) -> str:
        self.write_status(
            "generating_research_direction",
            {
                "note": "No queued READY specs. Project-owned ideation is generating one candidate through the registered provider.",
            },
        )
        try:
            result = subprocess.run(
                [sys.executable, "scripts/run_strategy_ideation_once.py"],
                cwd=self.repo_root,
                env=self.ideation_env(),
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                timeout=self.timeout_seconds,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            output = (exc.stdout or "") if isinstance(exc.stdout, str) else ""
            self.write_status(
                "ideation_timeout",
                {
                    "timeout_seconds": self.timeout_seconds,
                    "output": output[-4000:],
                    "note": "Provider or rewrite loop timed out; next tick may try again.",
                },
            )
            self.audit("ideation_timeout", {"timeout_seconds": self.timeout_seconds, "output": output[-4000:]})
            self.log(f"ideation timed out after {self.timeout_seconds} seconds")
            return "ideation_timeout"
        output = result.stdout or ""
        if result.returncode != 0:
            return self._handle_failed_ideation(result.returncode, output)
        try:
            payload = json.loads(output)
        except json.JSONDecodeError as exc:
            self.write_status("ideation_failed", {"error": f"JSONDecodeError: {exc}", "output": output[-4000:]})
            self.audit("ideation_failed", {"error": f"JSONDecodeError: {exc}"})
            return "ideation_failed"
        status = str(payload.get("status") or "")
        self.audit("ideate", {"status": status, "proposal_id": payload.get("proposal_id"), "spec_path": payload.get("spec_path")})
        if status == "READY":
            item = self.enqueue_ready_spec(state, payload)
            self.write_status("queued_ideation_spec", item)
            return "queued_ideation_spec"
        self.write_status("ideation_not_runnable", self._non_runnable_payload(status, payload))
        return "ideation_not_runnable"

    def generate_until_actionable(self, state: dict[str, Any], *, max_attempts: int = 1) -> str:
        last_result = "ideation_not_runnable"
        attempts: list[str] = []
        for _ in range(max_attempts):
            state = self.load_state()
            result = self.generate_next_spec_if_idle(state)
            attempts.append(result)
            last_result = result
            if result != "ideation_not_runnable":
                break
        if len(attempts) > 1:
            self.write_status(
                last_result,
                {
                    "ideation_attempts": attempts,
                    "note": "Processed multiple non-runnable drafts in one tick before stopping.",
                },
            )
        return last_result

    def _handle_failed_ideation(self, returncode: int, output: str) -> str:
        try:
            payload = json.loads(output)
        except json.JSONDecodeError:
            payload = {}
        payload_status = str(payload.get("status") or "")
        if payload_status in EXCLUDE_STATUSES:
            self.audit(
                "ideate",
                {
                    "status": payload_status,
                    "proposal_id": payload.get("proposal_id"),
                    "spec_path": payload.get("spec_path"),
                    "reason": payload.get("reason"),
                },
            )
            self.write_status("ideation_not_runnable", self._non_runnable_payload(payload_status, payload))
            return "ideation_not_runnable"
        if "executor_tool_code" in output or "returned empty content" in output:
            self.write_status(
                "executor_tool_response_invalid",
                {
                    "returncode": returncode,
                    "reason": "tool-code AI response was empty or invalid",
                    "output": output[-4000:],
                },
            )
            self.audit("executor_tool_response_invalid", {"returncode": returncode, "output": output[-4000:]})
            return "executor_tool_response_invalid"
        self.write_status("ideation_failed", {"returncode": returncode, "output": output[-4000:]})
        self.audit("ideation_failed", {"returncode": returncode, "output": output[-4000:]})
        self.log(f"ideation failed rc={returncode}: {output[-1000:]}")
        return "ideation_failed"

    @staticmethod
    def _non_runnable_payload(status: str, payload: dict[str, Any]) -> dict[str, Any]:
        return {
            "proposal_status": status,
            "proposal_id": payload.get("proposal_id"),
            "spec_path": payload.get("spec_path"),
            "implementation_plan_path": payload.get("implementation_plan_path"),
            "reason": payload.get("reason"),
            "errors": payload.get("errors"),
        }
