"""Tests for spot_idle_start.py — the auto-start counterpart to
spot_idle_shutdown.py.

Each test exercises one decision branch end-to-end by invoking the script
with --dry-run and a temporary state-path + queue-path. We do NOT touch
the real Tencent CVM API: tests that need to control the probed spot
state monkey-patch ``probe_spot_state`` in the imported module.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

import pytest
import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "spot_idle_start.py"


def _write_queue(path: Path, *, queued: list[str] | None = None, vm_id: str = "guangzhou_spot",
                  instance_id: str = "ins-test-123") -> None:
    queue = []
    for run_id in queued or []:
        queue.append({"id": run_id, "status": "queued"})
    state = {
        "queue": queue,
        "vm_hosts": [
            {"id": vm_id, "host": "ubuntu@1.2.3.4", "instance_id": instance_id},
        ],
    }
    path.write_text(yaml.safe_dump(state, allow_unicode=True, sort_keys=False), encoding="utf-8")


def _run(state_path: Path, queue_path: Path, shutdown_state: Path | None = None,
         spot_state: str = "STOPPED", extra_args: list[str] | None = None,
         force_probe_fail: bool = False):
    """Run spot_idle_start.py in dry-run mode, with probe_spot_state monkey-patched."""
    shim = REPO_ROOT / "scripts" / "_spot_start_probe_shim.py"
    shutdown_arg = str(shutdown_state) if shutdown_state else str(state_path) + ".shutdown"
    shim_src = (
        "# autogenerated test shim\n"
        "import sys, importlib.util\n"
        f"spec = importlib.util.spec_from_file_location('sis', {str(SCRIPT)!r})\n"
        "mod = importlib.util.module_from_spec(spec)\n"
        "spec.loader.exec_module(mod)\n"
        "def fake_probe(instance_id, region):\n"
        f"    if {force_probe_fail!r}:\n"
        "        raise RuntimeError('simulated probe failure')\n"
        f"    return ({spot_state!r}, 'Simulated')\n"
        "mod.probe_spot_state = fake_probe\n"
        "sys.argv = [\n"
        f"    {str(SCRIPT)!r},\n"
        f"    '--queue-path', {str(queue_path)!r},\n"
        f"    '--state-path', {str(state_path)!r},\n"
        f"    '--shutdown-state-path', {shutdown_arg!r},\n"
        "    '--dry-run',\n"
        f"] + {extra_args or []!r}\n"
        "raise SystemExit(mod.main())\n"
    )
    shim.write_text(shim_src, encoding="utf-8")
    try:
        result = subprocess.run(
            [sys.executable, str(shim)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=30,
            check=False,
        )
    finally:
        shim.unlink(missing_ok=True)
    return result


def _read_state(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def test_no_queue_writes_no_queue_and_returns_zero(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    _write_queue(queue, queued=[])  # empty
    r = _run(state, queue, spot_state="STOPPED")
    assert r.returncode == 0
    assert "no_queue" in r.stdout
    assert _read_state(state).get("last_status") == "no_queue"


def test_queue_unstable_first_tick_just_stamps(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    _write_queue(queue, queued=["r1"])
    # First tick: queued_since is just being stamped, stable window not yet reached.
    r = _run(state, queue, spot_state="STOPPED",
             extra_args=["--queued-stable-minutes", "5"])
    assert r.returncode == 0
    assert "queue_unstable_wait" in r.stdout
    saved = _read_state(state)
    assert saved.get("queued_since") is not None


def test_stop_cooldown_blocks_start(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    shutdown = tmp_path / "shutdown.json"
    _write_queue(queue, queued=["r1"])
    # Pretend the queue has been queued long enough.
    state.write_text(
        json.dumps({"queued_since": datetime.now(timezone.utc).timestamp() - 600,
                    "updated_at": "2026-05-24T00:00:00+00:00"}),
        encoding="utf-8",
    )
    # And spot was shutdown 1 minute ago — well inside the 10-min cooldown.
    one_minute_ago = datetime.now(timezone.utc) - timedelta(minutes=1)
    shutdown.write_text(
        json.dumps({"status": "shutdown_sent",
                    "updated_at": one_minute_ago.isoformat(timespec="seconds")}),
        encoding="utf-8",
    )
    r = _run(state, queue, shutdown_state=shutdown, spot_state="STOPPED")
    assert r.returncode == 0
    assert "stop_cooldown_wait" in r.stdout


def test_failed_start_backoff_blocks_retry(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    shutdown = tmp_path / "shutdown.json"
    _write_queue(queue, queued=["r1"])
    five_minutes_ago = datetime.now(timezone.utc) - timedelta(minutes=5)
    state.write_text(
        json.dumps({
            "queued_since": datetime.now(timezone.utc).timestamp() - 600,
            "last_status": "start_failed",
            "last_attempt_at": five_minutes_ago.isoformat(timespec="seconds"),
        }),
        encoding="utf-8",
    )
    # No shutdown record → cooldown not active. Backoff (30 min default) IS active.
    r = _run(state, queue, shutdown_state=shutdown, spot_state="STOPPED")
    assert r.returncode == 0
    assert "failed_start_backoff_wait" in r.stdout


def test_daily_cap_reached_blocks(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    _write_queue(queue, queued=["r1"])
    today = datetime.now(timezone.utc).date().isoformat()
    state.write_text(
        json.dumps({
            "queued_since": datetime.now(timezone.utc).timestamp() - 600,
            "daily_counter": {today: 6},  # equal to default --daily-cap
        }),
        encoding="utf-8",
    )
    r = _run(state, queue, spot_state="STOPPED")
    assert r.returncode == 0
    assert "daily_cap_reached" in r.stdout


def test_running_spot_skips_with_queued_since_reset(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    _write_queue(queue, queued=["r1"])
    state.write_text(
        json.dumps({"queued_since": datetime.now(timezone.utc).timestamp() - 600}),
        encoding="utf-8",
    )
    r = _run(state, queue, spot_state="RUNNING")
    assert r.returncode == 0
    assert "spot_not_stopped" in r.stdout
    saved = _read_state(state)
    # queued_since cleared so next idle->busy cycle re-starts the stable timer
    assert saved.get("queued_since") is None


def test_all_gates_pass_triggers_start_dry_run(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    _write_queue(queue, queued=["r1"])
    state.write_text(
        json.dumps({"queued_since": datetime.now(timezone.utc).timestamp() - 600}),
        encoding="utf-8",
    )
    r = _run(state, queue, spot_state="STOPPED")
    assert r.returncode == 0
    assert '"status": "started"' in r.stdout or '"status":"started"' in r.stdout
    saved = _read_state(state)
    assert saved.get("last_status") == "started"
    # daily_counter bumped
    today = datetime.now(timezone.utc).date().isoformat()
    assert int(saved.get("daily_counter", {}).get(today, 0)) == 1
    # queued_since reset so the same active queue doesn't re-trigger
    assert saved.get("queued_since") is None


def test_probe_failure_returns_nonzero_and_journals_error(tmp_path):
    queue = tmp_path / "q.yaml"
    state = tmp_path / "s.json"
    _write_queue(queue, queued=["r1"])
    state.write_text(
        json.dumps({"queued_since": datetime.now(timezone.utc).timestamp() - 600}),
        encoding="utf-8",
    )
    r = _run(state, queue, spot_state="STOPPED", force_probe_fail=True)
    assert r.returncode == 1
    assert "probe_failed" in r.stdout
    saved = _read_state(state)
    assert saved.get("last_status") == "probe_failed"
    assert "simulated probe failure" in saved.get("last_error", "")
